/** @type {import('tailwindcss').Config} */
// Tema portado de los diseños de Google Stitch (rama rediseno-stitch).
module.exports = {
  darkMode: "class",
  content: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
  theme: {
    extend: {
      colors: {
        "primary": "#3c51c2",
        "primary-container": "#566bdc",
        "primary-fixed": "#dee0ff",
        "primary-fixed-dim": "#bac3ff",
        "on-primary": "#ffffff",
        "on-primary-container": "#fffbff",
        "on-primary-fixed": "#00105c",
        "on-primary-fixed-variant": "#2339ab",
        "inverse-primary": "#bac3ff",
        "secondary": "#8135c5",
        "secondary-container": "#ba70ff",
        "secondary-fixed": "#f0dbff",
        "secondary-fixed-dim": "#deb7ff",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#440076",
        "on-secondary-fixed": "#2c0050",
        "on-secondary-fixed-variant": "#670fac",
        "tertiary": "#585c62",
        "tertiary-container": "#71757b",
        "tertiary-fixed": "#dfe2e9",
        "tertiary-fixed-dim": "#c3c7cd",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#fdfcff",
        "on-tertiary-fixed": "#181c21",
        "on-tertiary-fixed-variant": "#43474d",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "background": "#fcf9f8",
        "on-background": "#1c1b1b",
        "surface": "#fcf9f8",
        "surface-bright": "#fcf9f8",
        "surface-dim": "#dcd9d9",
        "surface-tint": "#3f53c4",
        "surface-variant": "#e5e2e1",
        "surface-container": "#f0eded",
        "surface-container-low": "#f6f3f2",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#eae7e7",
        "surface-container-highest": "#e5e2e1",
        "on-surface": "#1c1b1b",
        "on-surface-variant": "#454653",
        "inverse-surface": "#313030",
        "inverse-on-surface": "#f3f0ef",
        "outline": "#757685",
        "outline-variant": "#c5c5d5",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        "section-padding": "4rem",
        "component-gap": "1rem",
        "margin-page": "2.5rem",
        "gutter-grid": "1.5rem",
      },
      fontFamily: {
        "display-lg": ["Sora", "sans-serif"],
        "headline-lg": ["Sora", "sans-serif"],
        "headline-lg-mobile": ["Sora", "sans-serif"],
        "body-md": ["Sora", "sans-serif"],
        "body-sm": ["Sora", "sans-serif"],
        "label-caps": ["Sora", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
